### ISSUE TITLE
ietf-hardware: `Couldn't create a node with path '/ietf-hardware:hardware/component[name='ne:psu1']': LY_EEXIST`

### ISSUE THREAD

**Issue by jktjkt** [CESNET/velia#10]
Both PSUs were plugged in and working, the communication over I2C was OK as well. Despite that, the `ne:psu1` was listed as missing and in an active state:
```
line-MPW ~ # velia-list-alarms 
  Resource                    Severity  Detail                                                            Last raised                          Status
⏸  velia-hardware-g2.service   critical  systemd unit state: (activating, auto-restart)                    2024-10-31T20:45:06.844130601+00:00  active
⏸  cla-sdn-roadm-line.service  critical  systemd unit state: (failed, failed-before-auto-restart)          2024-10-31T20:45:08.082461021+00:00  active
⏶  ne:psu2:voltage-12V         critical  Sensor value is within normal parameters.                         2024-10-31T20:25:57.795033198+00:00  cleared
✕  ne:psu2                     critical  PSU is unplugged.                                                 2024-10-31T20:32:01.625128867+00:00  cleared
✕  ne:psu1                     critical  PSU is unplugged.                                                 2024-10-31T20:39:16.088226074+00:00  active
✕  ne:pdu                      critical  I2C read failure for PDU. Could not get hardware sensor details.  2024-10-31T20:39:15.625502741+00:00  cleared
⏶  ne:pdu:voltage-3V3          warning   Sensor value crossed high threshold (3406 > 3400).                2024-10-31T20:18:43.865476479+00:00  active
✕  ne:psu1:current-12V         warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:51.565369337+00:00  active
✕  ne:psu1:current-5Vsb        warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:52.014047451+00:00  active
✕  ne:psu1:current-in          warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:52.465722878+00:00  active
✕  ne:psu1:fan:fan1:rpm        warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:52.908984008+00:00  active
✕  ne:psu1:power-in            warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:53.352273255+00:00  active
✕  ne:psu1:power-out           warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:53.798611741+00:00  active
✕  ne:psu1:temperature-1       warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:54.244164317+00:00  active
✕  ne:psu1:temperature-2       warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:44:54.812787297+00:00  active
✕  ne:psu1:voltage-12V         warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:36:35.018113596+00:00  cleared
✕  ne:psu1:voltage-5Vsb        warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:36:35.404355509+00:00  cleared
✕  ne:psu1:voltage-in          warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:36:35.791495415+00:00  active
✕  ne:pdu:current-12V          warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:39:16.503147473+00:00  active
✕  ne:pdu:current-3V3          warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:39:16.916007426+00:00  active
✕  ne:pdu:current-5V           warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:39:17.328944532+00:00  active
✕  ne:pdu:power-12V            warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:39:17.740454594+00:00  active
✕  ne:pdu:power-3V3            warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:39:18.158784351+00:00  active
✕  ne:pdu:power-5V             warning   Sensor value not reported. Maybe the sensor was unplugged?        2024-10-31T20:39:18.633760429+00:00  active
```
That was bothering me, but I *think* that this is due to #9, so I tried to have that alarm cleared by unplugging the PSU module, waiting a little while, and plugging it back in. Then `velia-hardware` crashed:
```
2024-10-31T20:45:56.726921+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-low-value-alarm: critical for /ietf-hardware:hardware/component[name='ne:psu2:voltage-12V']
2024-10-31T20:45:59.041697+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-low-value-alarm: cleared for /ietf-hardware:hardware/component[name='ne:psu2:voltage-12V']
2024-10-31T20:46:02.927387+0000 line-MPW hardware[31099]: Couldn't read ne:psu1 sysfs data (maybe the device was just ejected?): Could not read int64_t value from '/sys/bus/i2c/devices/2-0058/hwmon/hwmon9/temp1_input'.
2024-10-31T20:46:02.928855+0000 line-MPW hardware[31099]: Deregistering ym2151 from I2C bus 2 address 0x58
2024-10-31T20:46:02.936425+0000 line-MPW hardware[31099]: Deregistering 24c02 from I2C bus 2 address 0x50
2024-10-31T20:46:04.465287+0000 line-MPW main[31099]: [PERFORMANCE][TOO_SLOW] void velia::alarms::push(sysrepo::Session, const std::string&, const std::string&, const std::string&, const std::string&) 1236ms
2024-10-31T20:46:04.465542+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:current-12V']
2024-10-31T20:46:04.467774+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:current-5Vsb']
2024-10-31T20:46:04.471292+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:current-in']
2024-10-31T20:46:04.472885+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:fan:fan1:rpm']
2024-10-31T20:46:04.474368+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:power-in']
2024-10-31T20:46:04.475798+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:power-out']
2024-10-31T20:46:04.477220+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:temperature-1']
2024-10-31T20:46:04.478641+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:temperature-2']
2024-10-31T20:46:04.480065+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:voltage-12V']
2024-10-31T20:46:04.938074+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:voltage-5Vsb']
2024-10-31T20:46:05.387548+0000 line-MPW hardware[31099]: Alarm velia-alarms:sensor-missing-alarm: warning for /ietf-hardware:hardware/component[name='ne:psu1:voltage-in']
2024-10-31T20:46:05.389615+0000 line-MPW main[31099]: [PERFORMANCE][TOO_SLOW] ietf-hardware/poll 2480ms
2024-10-31T20:46:07.108911+0000 line-MPW veliad-hardware[31099]: libyang[0]: Path "/ietf-hardware:hardware/component[name='ne:psu1']" already exists. (data path: /ietf-hardware:hardware/component[name='ne:psu1'])
2024-10-31T20:46:07.110126+0000 line-MPW veliad-hardware[31099]: terminate called after throwing an instance of 'libyang::ErrorWithCode'
2024-10-31T20:46:07.110126+0000 line-MPW veliad-hardware[31099]:   what():  Couldn't create a node with path '/ietf-hardware:hardware/component[name='ne:psu1']': LY_EEXIST
```
here's the BT:
```
(gdb) bt
#0  0xb67f7294 in ?? () from /lib/libc.so.6
#1  0xb67b1524 in raise () from /lib/libc.so.6
#2  0xb679c180 in abort () from /lib/libc.so.6
#3  0xb69e04b0 in __gnu_cxx::__verbose_terminate_handler() () from /lib/libstdc++.so.6
#4  0xb69de03c in ?? () from /lib/libstdc++.so.6
#5  0xb69de0c8 in std::terminate() () from /lib/libstdc++.so.6
#6  0xb69de41c in __cxa_throw () from /lib/libstdc++.so.6
#7  0xb6c3b608 in libyang::throwError (code=code@entry=4, msg=...) at /home/jkt/work/prog/_build/_br-cfb/build/libyang-cpp-custom/src/utils/exception.cpp:45
#8  0xb6c3b854 in libyang::throwIfError (code=4, msg=...) at /home/jkt/work/prog/_build/_br-cfb/build/libyang-cpp-custom/src/utils/exception.cpp:33
#9  0xb6c3c9ec in libyang::impl::newPath (node=node@entry=0x25ff828, ctx=ctx@entry=warning: could not convert 'ly_ctx' from the host encoding (ANSI_X3.4-1968) to UTF-32.
This normally should not happen, please file a bug report.
0x0, refs=..., path=..., value=..., options=...)
    at /home/jkt/work/prog/_build/_br-cfb/build/libyang-cpp-custom/src/utils/newPath.cpp:22
#10 0xb6c09b50 in libyang::DataNode::newPath (this=this@entry=0xb49fd3c0, path=..., value=..., options=...) at /home/jkt/work/prog/_build/_br-cfb/build/libyang-cpp-custom/src/DataNode.cpp:264
#11 0x005437d4 in velia::utils::valuesToYang (values=..., removePaths=..., discardPaths=..., session=..., parent=...)
    at /home/jkt/work/prog/_build/_br-cfb/per-package/velia/host/opt/ext-toolchain/arm-buildroot-linux-gnueabihf/include/c++/13.2.0/optional:213
#12 0x00544468 in velia::utils::valuesToYang (values=..., removePaths=..., discardPaths=..., session=..., parent=...) at /home/jkt/work/prog/_build/_br-cfb/build/velia-custom/src/utils/sysrepo.cpp:70
#13 0x00544948 in velia::utils::valuesPush (values=..., removePaths=..., discardPaths=..., session=...) at /home/jkt/work/prog/_build/_br-cfb/build/velia-custom/src/utils/sysrepo.cpp:126
#14 0x00545030 in velia::utils::valuesPush (values=..., removePaths=..., discardPaths=..., session=..., datastore=datastore@entry=sysrepo::Datastore::Operational)
    at /home/jkt/work/prog/_build/_br-cfb/build/velia-custom/src/utils/sysrepo.cpp:116
#15 0x00523dc8 in operator() (__closure=<optimized out>) at /home/jkt/work/prog/_build/_br-cfb/build/velia-custom/src/ietf-hardware/sysrepo/Sysrepo.cpp:148
#16 0xb6a0bdb4 in ?? () from /lib/libstdc++.so.6
#17 0xb67f534c in ?? () from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by jktjkt** [comment]
since the operational DS handling was rewritten both upstream and in this project, let's close this one.
